invmngr_application/auth.py
"""Routes for user authentication."""
from flask import Blueprint, redirect, render_template, flash, request, session, url_for
from flask_login import login_required, logout_user, current_user, login_user
from flask import current_app as app
from .forms import LoginForm, SignupForm
from .models import db, User
from .assets import compile_auth_assets
from . import login_manager

# Blueprint Configuration
auth_bp = Blueprint('auth_bp', __name__,
                    template_folder='templates',
                    static_folder='static')
compile_auth_assets(app)


@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    """
    User login page.

    GET: Serve Log-in page.
    POST: If form is valid and new user creation succeeds, redirect user to the logged-in homepage.
    """
    if current_user.is_authenticated:
        return redirect(url_for('main_bp.dashboard'))  # Bypass if user is logged in

    login_form = LoginForm()
    if request.method == 'POST':
        print(login_form.validate_on_submit())
        if login_form.validate_on_submit():
            email = login_form.get('email')
            password = login_form.get('password')
            print(email)
            user = User.query.filter_by(email=email).first()  # Validate Login Attempt
            if user and user.check_password(password=password):
                login_user(user)
                next_page = request.args.get('next')
                return redirect(next_page or url_for('main_bp.dashboard'))
        flash('Invalid username/password combination')
        return redirect(url_for('auth_bp.login'))

    return render_template('login.jinja2',
                           form=login_form,
                           title='Log in.',
                           template='login-page',
                           body="Log in with your User account.")


@auth_bp.route('/signup', methods=['GET', 'POST'])
def signup():
    """
    User sign-up page.

    GET: Serve sign-up page.
    POST: If creds are valid, redirect user to logged-in homepage.
    """
    signup_form = SignupForm()
    if request.method == 'POST':
        if signup_form.validate_on_submit():
            name = signup_form.get('name')
            email = signup_form.get('email')
            password = signup_form.get('password')
            website = signup_form.get('website')
            existing_user = User.query.filter_by(email=email).first()  # Check if user exists
            if existing_user is None:
                user = User(name=name,
                            email=email,
                            website=website)
                user.set_password(password)
                db.session.add(user)
                db.session.commit()  # Create new user
                login_user(user)  # Log in as newly created user
                return redirect(url_for('main_bp.dashboard'), code=400)
            flash('A user already exists with that email address.')
            return redirect(url_for('auth_bp.signup'))

    return render_template('signup.jinja2',
                           title='Create an Account.',
                           form=signup_form,
                           template='signup-page',
                           body="Sign up for a user account.")

@auth_bp.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("auth_bp.login"))

@login_manager.user_loader
def load_user(user_id):
    """Check if user is logged-in on every page load."""
    if user_id is not None:
        return User.query.get(user_id)
    return None


@login_manager.unauthorized_handler
def unauthorized():
    """Redirect unauthorized users to Login page."""
    flash('You must be logged in to view that page.')
    return redirect(url_for('auth_bp.login'))

invmngr_application/templates/adminerror.jinja2
{% extends "layout.jinja2" %}

{% block pagestyles %}
  <link href="{{ url_for('static', filename='src/css/main.css') }}" rel="stylesheet" type="text/css">
  <link rel="stylesheet" href="https://use.typekit.net/sus7rlu.css">
{% endblock %}

{% block content %}
    <h1>{{body}}</h1>

    <h4>You aren't supposed to be here...You're not an admin</h4>

{% endblock %}

invmngr_application/templates/dashboard.jinja2
{% extends "layout.jinja2" %}

{% block pagestyles %}
  <style type="text/css">
    #datatable * {
        border: 1px solid black;
        text-align: center;
    }
  </style>
  <link rel="stylesheet" href="https://use.typekit.net/sus7rlu.css">
{% endblock %}

{% block content %}

    {% if current_user.is_authenticated %}

        {% include "modals.jinja2" %}

        <div id="TblCtrl" >
            <select id="tbltoshow" name="tbltoshow">
                <option disabled selected style="display:none;">Select Table</option>
                {% if current_user.is_admin() %}
                    <option value="users">Users</option>
                {% endif %}
                <option value="parts">Parts</option>
                <option value="vendors">Vendors</option>
            </select>
            <p><a href=# id=calculate>Load Data</a></p>
        </div>

        <div style="position:relative;width:100%;margin-bottom:3em;">
            <a class="hidwhennotblandisnottitleorsearch" id="datatableaddthing" href="#additem" rel="modal:open" style="display:none;position:absolute;z-index:1;"><!-- Add Thing --></a>
            <input style="display:none;position:absolute;z-index:1;left:74%;" class="hidwhennotbl" type="text" id="datatablesearch" placeholder=" search"></input>
            <h4 class="hidwhennotbl" id="datatabletitle" style="display:none;text-align:center;position:absolute;width:100%;"></h4>
        </div>
        <table id="datatable" style="width:100%;border: 1px solid black;"></table>

    {% endif %}

    </div>

    <script type="text/javascript">
      $(function() {
        $('a#calculate').bind('click', function() {
          if (!$('select[name="tbltoshow"]').val()) return;
          $.getJSON($SCRIPT_ROOT + '/bg_gettbl', {
            tbltoshow: $('select[name="tbltoshow"]').val()
          }, function(data) {
            $("#datatable tr").remove();
            $("#datatabletitle").text(data.datatabletitle);
            var h;
            var $tr = $("<tr>").addClass("head");
            for (h of data.tblheaders) {
                let $th = $("<th>").css("font-weight","600");
                $tr.append( $th.text(h) );
            }
            $tr.appendTo("#datatable");
            var i;
            for (i of data.tbldata) {
                var $tr = $("<tr>");
                for (h of data.tblheaders) {
                    $tr.append( $("<td>").text( i[h] ) );
                }
                $tr.appendTo("#datatable");
            }
            $(".hidwhennotbl").show();
            if (data.datatabletitle != "Users") {
                $(".hidwhennotblandisnottitleorsearch").show();
                $("#datatableaddthing").attr("href", "#add{}".replace("{}",data.datatabletitle))
                $("#datatableaddthing").text("Add {}".replace("{}", data.datatabletitle.slice(0,-1)));
            }
            $("#datatable").autolink();
          });
          return false;
        });
      });
    </script>

    <script type="text/javascript">
        $("#datatablesearch").on("keyup", function() {
            var value = $(this).val();
            var patt = new RegExp(value, "i");

            $("#datatable tr").each(function(index) {

                if (!($(this).find('td').text().search(patt) >= 0)) {
                    $(this).not('#datatable .head').hide();
                }
                if (($(this).find('td').text().search(patt) >= 0)) {
                    $(this).show();
                }

            });
        })
</script>


<script type="text/javascript">
  $(function() {
        $('a#addvendor').bind('click', function() {
          if (!$('input[name="name"]').val() || !$('input[name="website"]').val()) return;
          $.getJSON($SCRIPT_ROOT + '/bg_add_vendor', {
            name: $('input[name="name"]').val(),
            website: $('input[name="website"]').val()
          }, function(data) {
            if (data.didok) {
                $("#vendormodalalert").html("Vendor added Successfully.");
            }
          });
        });
      });
    </script>

<script type="text/javascript">
  $(function() {
        $('a#addpart').bind('click', function() {
          if (!$('input[name="partnumber"]').val() || !$('input[name="description"]').val() || !$('input[name="unitprice"]').val() || !$('input[name="quantity"]').val() || !$('input[name="category"]').val() || !$('input[name="weblink"]').val() || !$('select[name="vendor"]').val()) return;
          $.getJSON($SCRIPT_ROOT + '/bg_add_part', {
            partnumber: $('input[name="partnumber"]').val(),
            description: $('input[name="description"]').val(),
            unitprice: $('input[name="unitprice"]').val(),
            quantity: $('input[name="quantity"]').val(),
            category: $('input[name="category"]').val(),
            weblink: $('input[name="weblink"]').val(),
            vendor: $('select[name="vendor"]').val()
          }, function(data) {
            if (data.didok) {
                $("#partmodalalert").html("Part added Successfully.");
            }
          });
        });
      });
</script>

    <script type="text/javascript">
        jQuery(function($) {
        var re = /((http|https|ftp):\/\/[a-zа-я0-9\w?=&.\/-;#~%-]+(?![a-zа-я0-9\w\s?&.\/;#~%"=-]*>))/g;
        function makeHTML(textNode) {
            var source = textNode.data;
            return source.replace(re, function() {
                var url = arguments[0];
                var a = $('<p></p>').attr({'onclick' : 'window.open(\'' + url + '\'); return false;','style': 'cursor:pointer;color:#007bff;margin:0;border:none;'}).text(url);
                return url.match(/^https?:\/\/$/) ? url : $('<div></div>').append(a).html();
            });
        };
        function eachText(node, callback) {
            $.each(node.childNodes, function() {
                if (this.nodeType != 8 && this.nodeName != 'A') {
                    this.nodeType != 1 ? callback(this) : eachText(this, callback);
                }
            });
        };
        $.fn.autolink = function() {
            return this.each(function() {
                var queue = [];
                eachText(this, function(e) {
                    var html = makeHTML(e);
                    if (html != e.data) {
                        queue.push([e, makeHTML(e)]);
                    }
                });
                $.each(queue, function(i, x) {
                    $(x[0]).replaceWith(x[1]);
                });
            });
        };
    });
</script>


{% endblock %}

invmngr_application/templates/layout.jinja2
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>{{title}}</title>
    <meta name="HandheldFriendly" content="True" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover" />
    <meta name="theme-color" content="#5eb9d7" />
    <link rel="shortcut icon" href="{{ url_for('static', filename='img/sbhs3gearlogo.png') }}" type="image/x-icon"/>
    {% block pagestyles %}{% endblock %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"/>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous"/>
    <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,500" rel="stylesheet"/>
  </head>

  <body class="{{template}}">
    {% block additionalscripts %}
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="{{url_for('static', filename='jquery.js') }}">\x3C/script>')</script>
        <script type="text/javascript">
            $SCRIPT_ROOT = {{ request.script_root|tojson|safe }};
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.js"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.css" />
    {% endblock %}
    <div class="container">
        {% if current_user.is_authenticated %}
        <div style="float: right" id="accountstuff">
            <p>Hi {{ current_user.name }}!</p>
            <a href="{{ url_for('auth_bp.logout') }}">Log out</a>
        </div>
        {% endif %}
      {% block content %}{% endblock %}
    </div>
  </body>

</html>

invmngr_application/templates/login.jinja2
{% extends "layout.jinja2" %}

{% block content %}
  <div class="formwrapper">
    <form method="POST">

      <div class="logo">
        <img width=64 height=64 src="{{ url_for('static', filename='img/sbhs3gearlogo.png') }}">
      </div>

      {% for message in get_flashed_messages() %}
        <div class="alert alert-warning">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ message }}
        </div>
      {% endfor %}

      <h1>Log In</h1>

      <fieldset class="email">
         {{ form.email.label }}
         {{ form.email(placeholder='youremail@example.com') }}
         {% if form.email.errors %}
           <ul class="errors">
             {% for error in form.email.errors %}<li>{{ error }}</li>{% endfor %}
           </ul>
         {% endif %}
      </fieldset>

      <fieldset class="password">
        {{ form.password.label }}
        {{ form.password }}
        {% if form.email.errors %}
          <ul class="errors">
            {% for error in form.password.errors %}<li>{{ error }}</li>{% endfor %}
          </ul>
        {% endif %}
      </fieldset>

      <div class="submitbutton">
        <input id="submit" type="submit" value="Submit">
      </div>

      <div class="loginsignup">
        <span>Don't have an account? <a href="{{ url_for('auth_bp.signup') }}">Sign up.</a></span>
        </div>
        
    </form>
  </div>
{% endblock %}

invmngr_application/templates/modals.jinja2
<div id="addParts" class="modal">
    <div class="formwrapper">
        <label for="partnumber">PartNumber:</label><input type="text" id="partnumber" name="partnumber"><br>
        <label for="description">Description:</label><input type="text" id="description" name="description"><br>
        <label for="unitprice">UnitPrice:</label><input type="number" min="0" id="unitprice" name="unitprice"><br>
        <label for="quantity">Quantity:</label><input type="number" min="0" id="quantity" name="quantity"><br>
        <label for="category">Category:</label><input type="text" id="category" name="category"><br>
        <label for="weblink">Weblink:</label><input type="url" id="weblink" name="weblink"><br>
        <label for="vendor">Vendor:</label><select id="vendor" name="vendor">
        {% for vendor in Vendors %}
            <option value="{{ vendor.name }}" >{{ vendor.name }}</option>
        {% endfor %}
        </select><br>
        <a href=# id=addpart>Add Part</a>
    </div>
    <p id="vendormodalalert" style="color:green;"></p>
    <a href="#" rel="modal:close">Close</a>
</div>

<div id="addVendors" class="modal">
    <div class="formwrapper">
        <label for="name">Name:</label><input type="text" id="name" name="name"><br>
        <label for="website">Website:</label><input type="url" id="website" name="website"><br>
        <a href=# id="addvendor">Add Vendor</a>
    </div>
    <p id="vendormodalalert" style="color:green;"></p>
    <a href="#" rel="modal:close">Close</a>
</div>

invmngr_application/templates/signup.jinja2
{% extends "layout.jinja2" %}

{% block content %}
  <div class="formwrapper">
    <form method="POST">

      <div class="logo">
        <img width=64 height=64 src="{{ url_for('static', filename='img/sbhs3gearlogo.png') }}">
      </div>

      {% for message in get_flashed_messages() %}
        <div class="alert alert-warning">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ message }}
        </div>
      {% endfor %}

      <h1>Sign Up</h1>

      <fieldset class="name">
        {{ form.name.label }}
        {{ form.name(placeholder='John Smith') }}
        {% if form.name.errors %}
          <ul class="errors">
            {% for error in form.email.errors %}<li>{{ error }}</li>{% endfor %}
          </ul>
        {% endif %}
      </fieldset>

      <fieldset class="email">
        {{ form.email.label }}
        {{ form.email(placeholder='foo@bar.com') }}
        {% if form.email.errors %}
          <ul class="errors">
            {% for error in form.email.errors %}<li>{{ error }}</li>{% endfor %}
          </ul>
        {% endif %}
      </fieldset>

      <fieldset class="password">
        {{ form.password.label }}
        {{ form.password }}
        {% if form.password.errors %}
          <ul class="errors">
            {% for error in form.password.errors %}<li>{{ error }}</li>{% endfor %}
          </ul>
        {% endif %}
      </fieldset>

      <fieldset class="confirm">
        {{ form.confirm.label }}
        {{ form.confirm }}
        {% if form.confirm.errors %}
          <ul class="errors">
            {% for error in form.confirm.errors %}<li>{{ error }}</li>{% endfor %}
          </ul>
        {% endif %}
      </fieldset>

      <div class="submitbutton">
        <input id="submit" type="submit" value="Submit">
      </div>

    </form>

    <div class="loginsignup">
      <span>Already have an account? <a href="{{ url_for('auth_bp.login') }}">Log in.</a></span>
    </div>
  </div>
{% endblock %}